# Generated by Django 4.0.4 on 2022-11-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=10000)),
                ('question_amount', models.IntegerField()),
                ('test_text', models.CharField(max_length=10000)),
                ('test_answer', models.CharField(max_length=10000)),
                ('test_score', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('players_amount', models.IntegerField()),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('game_mode', models.CharField(max_length=100)),
                ('question_amount', models.IntegerField()),
                ('test_time', models.CharField(max_length=10000)),
                ('max_score', models.IntegerField()),
                ('users_passed', models.CharField(max_length=1000000)),
                ('teams_passed', models.CharField(max_length=1000000)),
                ('teams_mark', models.CharField(max_length=1000000)),
                ('users_answers', models.CharField(max_length=1000000)),
                ('users_marks', models.CharField(max_length=1000000)),
            ],
        ),
    ]
