# Generated by Django 4.0.4 on 2022-11-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estafetaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='teams_mark',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='tests',
            name='teams_passed',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='tests',
            name='users_answers',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='tests',
            name='users_marks',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='tests',
            name='users_passed',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
