# Generated by Django 4.0.4 on 2022-11-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estafetaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='test_time',
        ),
    ]
